### ISSUE TITLE
add graphics

### ISSUE THREAD

**Issue by hofmannv** [Materials-Data-Science-and-Informatics/survey_dashboard#13]
add boxes with graphics & numbers: 
- [x] number of participats
- [x] number of Rearch areas "surveyed" 
- [x] link to data
-

**Comment by broeder-j** [comment]
We have now this: 
```
631 Researchers took part in the survey

18 Helmholtz research centers and institutes

49 Survey questions
```

and the data is linked in the text. If you want we could still add something about the research areas or create an icon for the dataset.

**Comment by hofmannv** [comment]
i htink it would be good to iconofy the link to the dataset instead of "hiding" it in the text

**Comment by hofmannv** [comment]
maybe it would also be good to add a github icon linking to this issue board and write "feedback and suggestions welcome"

**Comment by broeder-j** [comment]
Currently there is a github icon in the footer linking to this repository. But if the sentence 'Any Feedback is welcome and can be given [here](https://github.com/Materials-Data-Science-and-Informatics/survey_dashboard)' stays we could add an icon with a link after this. 

 I would not put the icon directly near the others, also because this link is ONLY for feedback for the dashboard, not for feedback to the overall survey.
